services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: ledgerd-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Listeners
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,HOST://0.0.0.0:9092
      # Advertised
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # Overrides
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # default is 3 for prod. Must be >= node count which in local's case, is 1. Same reasoning for the 2 below
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 # default is 3 which is useful in production to let consumers settle in, better 0 for local for easier testing
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" # default is true. But false here to prevent typos from getting through.
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
  postgres:
    image: postgres:17.10
    container_name: ledgerd-postgres
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: ledgerd
      POSTGRES_USER: ledgerd
      POSTGRES_PASSWORD: ledgerd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledgerd -d ledgerd"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  postgres-data: 