spring:
  application:
    name: ledgerd
  datasource:
    url: jdbc:postgresql://localhost:5433/ledgerd
    username: ledgerd
    password: ledgerd
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092